(provide 'org_config)

;; Use org from GNU ELPA (org-plus-contrib is defunct)
(use-package org :pin gnu)

;; indent the first line of paragraph in org mode 
(setq org-adapt-indentation t)

(setq org-html-validation-link nil)
(add-hook 'org-mode-hook 'flyspell-mode)
(setq org-log-done 'time)
;; org-model keybinding
(add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
;; (global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
;; (global-set-key "\C-cb" 'org-iswitchb)
;; clock task

;; (setq org-clock-persist 'history)
;; (org-clock-persistence-insinuate)

(defun open-mytodo ()
  (interactive)
  (find-file "~/Dropbox/org/mytodo.org")
  (end-of-buffer)
  )

(defun open-work ()
  (interactive)
  (find-file "~/Dropbox/org/work.org")
  ;;(end-of-buffer)
  )

(defun open-personal ()
  (interactive)
  (find-file "~/Dropbox/org/personal.org")
  ;;(end-of-buffer)
  )

(defun open-notes ()
  (interactive)
  (find-file "~/Dropbox/org/notes.org")
  ;;(end-of-buffer)
  )

(defun open-english ()
  (interactive)
  (find-file "~/Dropbox/org/english_learning.org")
  ;;(end-of-buffer)
  )

(defun open-log ()
  (interactive)
  (find-file "~/Dropbox/org/log.org")
  ;;(end-of-buffer)
  )

(setq org-agenda-files (quote ("~/Dropbox/org/work.org" "~/Dropbox/org/personal.org" "~/Dropbox/org/log.org")))

;; Babel config
(defun my-org-confirm-babel-evaluate (lang body)
  (not (member lang '("C" "clojure" "sh" "plantuml"))))

(setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
;; coding in org
(org-babel-do-load-languages
 'org-babel-load-languages
 '( (perl . t)
    (ruby . t)
    (shell . t)
    (python . t)
    (emacs-lisp . t)
    (matlab . t)
    (C . t)
    (plantuml . t)))

;; ;; org reveal
;; ;; find more theme under site-lisp/reveal.js-master/css/theme
;; ;; (add-to-list 'load-path "~/Dropbox/emacs/site-lisp/org-reveal")
;; (require 'ox-reveal)
;; (setq org-reveal-root "file:///home/cgliu/Dropbox/emacs/site-lisp/reveal.js-master")
;; (setq org-reveal-mathjax t)

;; (cond ((eq system-type 'windows-nt) (load-library "ntemacs-cygwin"))
;;       ((eq system-type 'gnu/linux) (load-library "linux"))
;;       (t (load-library "default")))
;; PDFs visited in Org-mode are opened in Evince (and not in the default choice) http://stackoverflow.com/a/8836108/789593
(cond ((eq system-type 'gnu/linux)
       (add-hook 'org-mode-hook
		 #'(lambda ()
		    (delete '("\\.pdf\\'" . default) org-file-apps)
		    (add-to-list 'org-file-apps '("\\.pdf\\'" . "evince %s"))
                    (add-to-list 'org-file-apps '("\\.x?html?\\'" . "/usr/bin/firefox %s"))
                    )))
      )

(setq org-agenda-custom-commands
      '(
        ("X" agenda "" nil ("~/Dropbox/emacs/org/agenda.html" ))
        ("Y" alltodo "" nil ("~/Dropbox/emacs/org/todo.html" ))
        ;; 	("h" "Agenda and Home-related tasks"
        ;; 	 ((agenda "")
        ;; 	  (tags-todo "home")
        ;; 	  (tags "garden"))
        ;; 	 nil
        ;; 	 ("~/org/home.html"))
        ;; 	("o" "Agenda and Office-related tasks"
        ;; 	 ((agenda)
        ;; 	  (tags-todo "work")
        ;; 	  (tags "office"))
        ;; 	 nil
        ;; 	 ("~/org/office.html" ))
        ))

(setq org-remember-templates
      '(
        ("Notes" ?n "** %^{Title} %U %^g\n%?" "~/GTD/notes.org" "Notes")
        ("words" ?w "** %^{New Word} %u\n%? %&" "~/org/Source/Notes/english_learning.org" "Words")
        ("sentence"?s "** %?" "~/org/Source/Notes/english_learning.org" "Sentences")
        ("Todo" ?t "** TODO %^{Brief Description} %^g\nAdded: %U\n%?"
         "~/GTD/newgtd.org" "Tasks")
        ("Daily Track"  ?k "** %U\n%?%&" "~/GTD/journal.org" "Daily Track")
        ("Daily Review" ?r "** %t \n%[~/.daily_review.txt]\n"
         "~/GTD/journal.org" "Daily Review")
        ))

;; inline LaTex formula
(setq org-export-with-LaTeX-fragments nil)

;; my function
(require 'org-ref)
;; sandbox



(defun org-mode-reftex-setup ()
  (load-library "reftex")
  (and (buffer-file-name)
       (file-exists-p (buffer-file-name))
       (reftex-parse-all))
  (define-key org-mode-map (kbd "C-c )") 'reftex-citation)
  )

(add-hook 'org-mode-hook 'org-mode-reftex-setup)

;; (setq org-agenda-files (quote ("~/org/work.org" "~/org/mytodo.org" "~/org/job.org" "e:/SJTU/todo.org")))

;;see detail in org-html.org: org-export-html-postamble-format
(setq org-export-html-postamble "
<p class=\"Email\">Email: %e</p>
<p class=\"Last Modified\">Last modified %d using %c</p>
")

;; (setq org-export-html-postamble
;;       "<p class=\"author\">Author: %a (%e)</p>\t<p class=\"date\">Date: %d</p>\t<p class=\"creator\">Generated by %c</p>\n")



(setq org-plantuml-jar-path (expand-file-name "~/local/bin/plantuml.jar"))

;; support Chinese
(setq-default TeX-engine 'xetex)
(setq org-latex-to-pdf-process 
      '("xelatex -interaction nonstopmode %f"
        "xelatex -interaction nonstopmode %f")) ;; for multiple passes

(define-key org-mode-map (kbd "<f6>") 'org-latex-export-to-pdf)

;; Graduated heading sizes
(with-eval-after-load 'org
  (set-face-attribute 'org-level-1 nil :height 1.3 :weight 'bold)
  (set-face-attribute 'org-level-2 nil :height 1.2 :weight 'bold)
  (set-face-attribute 'org-level-3 nil :height 1.1 :weight 'bold)
  (set-face-attribute 'org-document-title nil :height 1.4 :weight 'bold))

;; org-modern: pretty bullets, tables, timestamps, tags
(use-package org-modern
  :ensure t
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-star '("◉" "○" "◈" "◇" "▸")
        org-modern-hide-stars nil))

;; Visual polish
(setq org-startup-with-inline-images t
      org-hide-emphasis-markers t
      org-pretty-entities t
      org-ellipsis " ▾")
(add-hook 'org-mode-hook #'org-indent-mode)
(add-hook 'org-mode-hook (lambda () (setq-local line-spacing 0.1)))

;; Inline image sizing (default 50% of window width)
(setq org-image-actual-width nil)
(advice-add 'org--create-inline-image :filter-args
            (lambda (args)
              (let ((file (nth 0 args))
                    (width (nth 1 args)))
                (list file (or width (truncate (* 0.5 (window-pixel-width))))))))

;; Open links in current window
(setq org-link-frame-setup
      '((vm . vm-visit-folder-other-frame)
        (vm-imap . vm-visit-imap-folder-other-frame)
        (gnus . org-gnus-no-new-news)
        (file . find-file)
        (wl . wl-other-frame)))



(setq org-html-htmlize-output-type 'inline-css)
(setq org-publish-project-alist
      '(("local"
         :base-directory "."
         :publishing-directory "."
         :publishing-function org-html-publish-to-html)

        ("my-site"
         :components ("org-files" "static-files"))

        ("org-files"
         :base-directory "~/Dropbox/post/"
         :publishing-directory "~/public_html/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :auto-sitemap t                  ; Enable sitemap/index
         :sitemap-filename "index.org"    ; Name of index file
         :sitemap-title "Frank Liu's Internal Website"         ; Title for index page
         :sitemap-function my-sitemap-function
         :completion-function (lambda (plist)
                                (shell-command "~/bin/org-sync.sh")))

        ("static-files"
         :base-directory "~/Dropbox/post/"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|svg\\|py"
         :publishing-directory "~/public_html/"
         :recursive t
         :publishing-function org-publish-attachment)))

(defun my-sitemap-function (title list)
  "Custom sitemap with headers"
  (concat "#+TITLE: " title "\n"
          "#+OPTIONS: toc:nil ^:{}\n\n"
          (org-list-to-org list)))
(require 'ox-reveal)
(use-package ox-reveal
  :ensure t
  :config
  (setq org-reveal-root "https://cdn.jsdelivr.net/npm/reveal.js"))

(defun my/org-export-with-dark-theme (orig-fun &rest args)
  (let ((current-theme (car custom-enabled-themes)))
    (load-theme 'manoj-dark t)  ; or your preferred dark theme
    (unwind-protect
        (apply orig-fun args)
      (when current-theme
        (load-theme current-theme t)))))

(advice-add 'org-html-export-to-html :around #'my/org-export-with-dark-theme)

(setq org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "WAITING(w@/!)" "PROJECT(p)" 
                                    "|"
                                    "DONE(d/!)" "CANCELLED(c@/!)")))

(setq org-html-head "<style> body { background-color: #FFFDE7; } em, i { color: red; } mjx-container { padding: 4px 8px; } pre, code { background-color: #1e1e2e; color: #cdd6f4; padding: 4px 8px; border-radius: 4px; } </style>")

(setq org-export-with-toc nil)
(setq org-export-with-section-numbers nil)

(setq org-html-postamble nil)
;; disable underscore 
(setq org-export-with-sub-superscripts nil)

(defun my/publish-org-files ()
  "Publish all .org files in the current directory to HTML in the same directory."
  (interactive)
  (let ((dir (file-name-directory (or buffer-file-name default-directory))))
    (org-publish
     `("tmp-publish"
       :base-directory ,dir
       :publishing-directory ,dir
       :base-extension "org"
       :publishing-function org-html-publish-to-html)
     t)))
